import { useState } from "react";
import FaqCard from "./FaqCard";

const FaqSection = () => {
  const faqs = [
    {
      icon: "/images/faq.webp",
      title: "What is zksyncstaking?",
      description: "ZK staking is the process of locking a certain...",
      content: `ZK staking is the process of locking a certain amount of cryptocurrency in your wallet to support the operation of the Zksync Era blockchain network. In return for staking your assets, you can receive rewards in ZK tokens.`,
    },
    {
      icon: "/images/faq.webp",
      title: "How does the staking platform work?",
      description:
        "The staking platform allows users to stake cryptocurrencies...",
      content: `The staking platform allows users to stake cryptocurrencies easily by depositing them into a secure wallet. Staked assets contribute to the security and operation of the network and receive rewards based on the staked amount and staking period.`,
    },
    {
      icon: "/images/faq.webp",
      title: "What is the APY offered on the platform?",
      description: "It offers an annual yield (APY) of 8.7%...",
      content: `It offers an annual yield (APY) of 8.7% for staked assets. However, the first 100 users will receive an exclusive promotional rate of 13.5% APY for the initial staking.`,
    },
    {
      icon: "/images/faq.webp",
      title: "What cryptocurrencies can I stake on the platform?",
      description: "For ZKsync token",
      content: `Currently, only Zksync tokens are supported.`,
    },
    {
      icon: "/images/faq.webp",
      title: "What is the minimum amount required to start staking?",
      description: "100 ZK is minimum",
      content: `The minimum staking amount for ZK is 100. This allows users to participate and receive rewards without investing a large amount of money.`,
    },
    {
      icon: "/images/faq.webp",
      title: "How often are rewards paid out?",
      description: "Rewards are paid out at any time",
      content: `Rewards are paid out at any time. You can check your accumulated rewards at any time on your dashboard.`,
    },
    {
      icon: "/images/faq.webp",
      title: "What happens to my staked assets?",
      description: "Staked assets are used to generate income...",
      content: `
            Staked assets are used to generate income with MEV bots.
            Users receive rewards from the profits generated by MEV.`,
    },
    {
      icon: "/images/faq.webp",
      title: "When can I unstake my assets?",
      description: "Staking may or may not be possible early depending...",
      content: `
            Staking may or may not be possible early depending on the terms of the staking contract.
            Users can withdraw at any time.`,
    },
    {
      icon: "/images/faq.webp",
      title: "How safe is my investment on the platform?",
      description:
        "Security is our top priority, and we use advanced encryption...",
      content: `Security is our top priority, and we use advanced encryption protocols. Our platform is designed to protect users’ funds and personal information.`,
    },
    {
      icon: "/images/faq.webp",
      title: "Who can I contact for support?",
      description:
        "Our support team is available to help you with any questions...",
      content: `Our support team is available to help you with any questions or concerns. Please contact zksyncstaking@gmail.com or https://t.me/zksyncstaking`,
    },
    {
      icon: "/images/faq.webp",
      title: "Do I have to pay a fee for staking?",
      description: "A 0.25% fee is charged for staking and unstaking...",
      content: `A 0.25% fee is charged for staking and unstaking on the platform. This fee is applied to maintain and improve the platform infrastructure, providing a safe and reliable staking experience for all users. This fee also contributes to the long-term locking of assets, supporting network stability and security. We strive to provide excellent service and reliable returns for staked assets while maintaining competitive fees.`,
    },
  ];

  const [current, setCurrent] = useState<number>(-1);

  return (
    <div className="xl:px-28 px-6 lg:px-12 flex flex-col  gap-4 mt-20 mb-10 ">
      <h2 className={`text-5xl font-bold text-white`}>FAQ</h2>
      {faqs.map((val, index) => (
        <FaqCard
          title={val.title}
          key={index}
          icon={val.icon}
          description={val.description}
          isExpended={index === current}
          onToggle={() => {
            if (index === current) setCurrent(-1);
            else setCurrent(index);
          }}
        >
          {val.content}
        </FaqCard>
      ))}
    </div>
  );
};

export default FaqSection;
